name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/build-deploy
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        source-directory: build
        build-command: npm run build
        custom-domain: ioanaorca.com
